name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.SEMANTIC_RELEASE }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
