# run checks and tests, release if everything pass, github-actions will create a new commit to bump version and update CHANGELOG.md

name: release

on:
  workflow_dispatch:
  schedule:
    # scheduled to release every 14th of month
    - cron:  '0 0 14 * *'

jobs:
  checks:
    if: (github.event.commits[0].author.name != 'github-actions') && (github.ref == 'refs/heads/master')
    uses: ./.github/workflows/test.yml

  release:
    needs: checks
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - name: View author
      run: echo "${{ github.event.commits[0].author.name }} ."

    - uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0
        persist-credentials: false

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.SEMANTIC_RELEASE }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
